name: myanimelist
description: The best way to explore all anime and manga.

publish_to: 'none'

version: 1.6.0+20

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  community_charts_flutter: ^1.0.4
  cloud_firestore: ^6.1.1
  expandable: ^5.0.1
  firebase_analytics: ^12.1.0
  firebase_core: ^4.3.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1
  firebase_remote_config: ^6.1.3
  flutter_pagewise: ^2.0.4
  flutter_web_auth_2: ^5.0.0
  fluttertoast: ^9.0.0
  font_awesome_flutter: ^10.12.0
  intl: ^0.20.2
  jikan_api: ^2.3.0
  package_info_plus: ^9.0.0
  photo_view: ^0.15.0
  provider: ^6.1.5
  rate_my_app: ^2.3.2
  shared_preferences: ^2.5.4
  slack_notifier: ^1.4.1
  smooth_page_indicator: ^2.0.1
  url_launcher: ^6.3.2
  xml: ^6.6.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "images/maneki.png"

flutter_native_splash:
  android: true
  ios: false
  image: "images/maneki.png"
  color: "f5f5f5"

flutter:
  uses-material-design: true
  assets:
    - images/
